baseURL = "https://verschwoerhaus.de"
title = "verschwoerhaus"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
languageCode = "de-DE"
theme = "twentysixteen"
paginate = 10

[params]
siteLogoUrl = "/wp-content/uploads/2016/10/cropped-Logo_VSH_RZ-1.jpg"

[permalinks]
  posts = "/:slug"
  post = "/:slug"
  page = "/:slug"
  pages = "/:slug"
  category = "/category/:slug"
  categories = "/category/:slug"
  tag = "/tag/:slug"
  tags = "/tag/:slug"

[languages]
  [languages.de]
    weight = 1
    languageName = "Deutsch"
    [[languages.de.menu.main]]
      identifier = "impressum"
      name = "Impressum"
      url = "/impressum/"
      weight = -100

    [[languages.de.menu.main]]
      parent = "impressum"
      identifier = "privacy"
      name = "Datenschutzerklärung"
      url = "/datenschutzerklaerung/"

    [[languages.de.menu.main]]
      parent = "impressum"
      identifier = "kontakt"
      name = "Kontakt"
      url = "/kontakt/"

    [[languages.de.menu.main]]
      parent = "impressum"
      identifier = "presse-logos-und-bilder"
      name = "Presse, Logos und Bilder"
      url = "/presse-logos-und-bilder/"

    [[languages.de.menu.main]]
      identifier = "termine-und-oeffnungszeiten"
      name = "Termine und Öffnungszeiten"
      url = "/termine-und-oeffnungszeiten/"
      weight = -90

    [[languages.de.menu.main]]
      identifier = "das-haus"
      name = "Das Haus"
      url = "/das-verschwoerhaus/"
      weight = -80

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "tour"
      name = "virtuelle Tour"
      url = "https://verschwoerhaus.de/tour/"

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "bibliothek"
      name = "Bibliothek"
      url = "/bibliothek/"

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "wiki"
      name = "Wiki"
      url = "https://wiki.verschwoerhaus.de"

    [[languages.de.menu.main]]
      identifier = "jhlab"
      name = "Jugend hackt Lab"
      url = "/category/jugend-hackt-lab/"
      weight = -70

    [[languages.de.menu.main]]
      identifier = "cookies"
      name = "Cookie Policy"
      url = "/cookie-policy/"
      weight = -60

    [[languages.de.menu.footer]]
      identifier = "privacy"
      name = "Datenschutzerklärung"
      url = "/datenschutzerklaerung/"

    [[languages.de.menu.social]]
      name = "verschwoerhaus auf Twitter"
      url = "https://twitter.com/verschwoerhaus"

    [[languages.de.menu.social]]
      name = "verschwoerhaus auf GitHub"
      url = "https://github.com/verschwoerhaus"

    [[languages.de.menu.social]]
      name = "verschwoerhaus auf YouTube"
      url = "https://www.youtube.com/channel/UChI22atUFzyO-E40Ks3Wrlg"

  [languages.en]
    weight = 2
    languageCode = "en-us"
    languageName = "English"

    [[languages.en.menu.main]]
      identifier = "impressum"
      name = "Impressum"
      url = "/impressum/"
      weight = -100

    [[languages.en.menu.main]]
      parent = "impressum"
      identifier = "privacy"
      name = "Privacy Policy"
      url = "/datenschutzerklaerung/"

    [[languages.en.menu.main]]
      parent = "impressum"
      identifier = "kontakt"
      name = "Contact"
      url = "/kontakt/"

    [[languages.en.menu.main]]
      parent = "impressum"
      identifier = "presse-logos-und-bilder"
      name = "Press, Logos and Photos"
      url = "/presse-logos-und-bilder/"

    [[languages.en.menu.main]]
      identifier = "termine-und-oeffnungszeiten"
      name = "Events and Opening Hours"
      url = "/termine-und-oeffnungszeiten/"
      weight = -90

    [[languages.en.menu.main]]
      identifier = "das-haus"
      name = "The House"
      url = "/das-verschwoerhaus/"
      weight = -80

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "tour"
      name = "virtual Tour"
      url = "https://verschwoerhaus.de/tour/"

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "bibliothek"
      name = "Library"
      url = "/bibliothek/"

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "wiki"
      name = "Wiki"
      url = "https://wiki.verschwoerhaus.de"

    [[languages.en.menu.main]]
      identifier = "jhlab"
      name = "Jugend hackt Lab"
      url = "/category/jugend-hackt-lab/"
      weight = -70

    [[languages.en.menu.main]]
      identifier = "cookies"
      name = "Cookie Policy"
      url = "/cookie-policy/"
      weight = -60

    [[languages.en.menu.footer]]
      identifier = "privacy"
      name = "Privacy Policy"
      url = "/datenschutzerklaerung/"

    [[languages.en.menu.social]]
      name = "verschwoerhaus on Twitter"
      url = "https://twitter.com/verschwoerhaus"

    [[languages.en.menu.social]]
      name = "verschwoerhaus on GitHub"
      url = "https://github.com/verschwoerhaus"

    [[languages.en.menu.social]]
      name = "verschwoerhaus on YouTube"
      url = "https://www.youtube.com/channel/UChI22atUFzyO-E40Ks3Wrlg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
