baseURL = ""
title = "verschwoerhaus"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
languageCode = "de-DE"
theme = "twentysixteen"
paginate = 10
enableRobotsTXT = true

[params]
siteLogoUrl = "/spaceicons/logo.svg"

[permalinks]
  posts = "/:slug"
  post = "/:slug"
  page = "/:slug"
  pages = "/:slug"
  category = "/category/:slug"
  categories = "/category/:slug"
  tag = "/tag/:slug"
  tags = "/tag/:slug"

[languages]
  [languages.de]
    weight = 1
    languageName = "Deutsch"

    [[languages.de.menu.main]]
      identifier = "das-haus"
      name = "Das Haus"
      url = "/das-verschwoerhaus/"
      weight = -100

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "tour"
      name = "virtuelle Tour"
      url = "/tour/"

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "bibliothek"
      name = "Bibliothek"
      url = "/bibliothek/"

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "presse"
      name = "Presseberichte"
      url = "/presse/"

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "logos-und-bilder"
      name = "Logos und Bilder"
      url = "/presse-logos-und-bilder/"

    [[languages.de.menu.main]]
      identifier = "termine-und-oeffnungszeiten"
      name = "Events, Gruppen & regelmäßige Termine"
      url = "/termine-und-oeffnungszeiten/"
      weight = -90

    [[languages.de.menu.main]]
      identifier = "wiki"
      name = "Wiki"
      url = "https://wiki.verschwoerhaus.de"
      weight = -80

    [[languages.de.menu.main]]
      identifier = "jhlab"
      name = "Jugend hackt Lab"
      url = "/category/jugend-hackt-lab/"
      weight = -70

    [[languages.de.menu.main]]
      identifier = "kontakt"
      name = "Kontakt"
      url = "/kontakt/"
      weight = -60

    [[languages.de.menu.main]]
      parent = "kontakt"
      identifier = "impressum"
      name = "Impressum"
      url = "/impressum/"

    [[languages.de.menu.footer]]
      identifier = "privacy"
      name = "Datenschutzerklärung"
      url = "/datenschutzerklaerung/"

    [[languages.de.menu.footer]]
      identifier = "cookies"
      name = "Cookie Policy"
      url = "/cookie-policy/"

    [[languages.de.menu.footer]]
      identifier = "impressum"
      name = "Impressum"
      url = "/impressum/"

    [[languages.de.menu.footer]]
      identifier = "rsslink"
      name = "RSS Feed"
      url = "/posts/index.xml"

    [[languages.de.menu.social]]
      name = "verschwoerhaus auf Twitter"
      url = "https://twitter.com/verschwoerhaus"

    [[languages.de.menu.social]]
      name = "verschwoerhaus auf GitHub"
      url = "https://github.com/verschwoerhaus"

    [[languages.de.menu.social]]
      name = "verschwoerhaus auf YouTube"
      url = "https://www.youtube.com/channel/UChI22atUFzyO-E40Ks3Wrlg"

    [[languages.de.menu.social]]
      name = "verschwoerhaus auf Instagram"
      url = "https://www.instagram.com/verschwoerhaus/"

  [languages.en]
    weight = 2
    languageCode = "en-us"
    languageName = "English"


    [[languages.en.menu.main]]
      identifier = "das-haus"
      name = "The House"
      url = "/en/das-verschwoerhaus/"
      weight = -100

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "tour"
      name = "virtual Tour"
      url = "/en/tour/"

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "bibliothek"
      name = "Library"
      url = "/en/bibliothek/"

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "presse"
      name = "Press"
      url = "/en/presse/"

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "logos-und-bilder"
      name = "Logos and Photos"
      url = "/en/presse-logos-und-bilder/"

    [[languages.en.menu.main]]
      identifier = "termine-und-oeffnungszeiten"
      name = "Events, Groups and Opening Hours"
      url = "/en/termine-und-oeffnungszeiten/"
      weight = -90

    [[languages.en.menu.main]]
      identifier = "wiki"
      name = "Wiki"
      url = "https://wiki.verschwoerhaus.de"
      weight = -80

    [[languages.en.menu.main]]
      identifier = "jhlab"
      name = "Jugend hackt Lab"
      url = "/en/category/jugend-hackt-lab/"
      weight = -70

    [[languages.en.menu.main]]
      identifier = "kontakt"
      name = "Contact"
      url = "/en/kontakt/"
      weight = -60

    [[languages.en.menu.main]]
      parent = "kontakt"
      identifier = "impressum"
      name = "Impressum"
      url = "/en/impressum/"

    [[languages.en.menu.footer]]
      identifier = "privacy"
      name = "Privacy Policy"
      url = "/en/datenschutzerklaerung/"

    [[languages.en.menu.footer]]
      name = "Cookie Policy"
      url = "/en/cookie-policy/"
      weight = -60

    [[languages.en.menu.footer]]
      identifier = "rsslink"
      name = "RSS Feed"
      url = "/en/posts/index.xml"

    [[languages.en.menu.social]]
      name = "verschwoerhaus on Twitter"
      url = "https://twitter.com/verschwoerhaus"

    [[languages.en.menu.social]]
      name = "verschwoerhaus on GitHub"
      url = "https://github.com/verschwoerhaus"

    [[languages.en.menu.social]]
      name = "verschwoerhaus on YouTube"
      url = "https://www.youtube.com/channel/UChI22atUFzyO-E40Ks3Wrlg"

    [[languages.en.menu.social]]
      name = "verschwoerhaus on Instagram"
      url = "https://www.instagram.com/verschwoerhaus/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
