backend:
  name: github
  repo: verschwoerhaus/verschwoerhaus.de
  branch: main
  use_graphql: true
  site_domain: vshde.netlify.app

media_folder: "/static/wp-content/uploads"
public_folder: "/wp-content/uploads"

locale: 'de'

i18n:
  structure: multiple_files
  locales: [de, en]
  default_locale: de

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/posts" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    create: true # Allow users to create new documents in this collection
    i18n: true
    media_folder: '{{media_folder}}/{{year}}/{{month}}'
    public_folder: '{{public_folder}}/{{year}}/{{month}}'
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "featured_image", widget: "image", required: false}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}
  - name: "categories"
    label: "Kategorieseiten"
    files:
      - file: "content/categories/jugend-hackt-lab/_index.md"
        label: "Jugend hackt Lab Übersicht"
        name: "category-jugend-hackt-lab"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "taxonomy_description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    path: "{{slug}}/index"
    extension: "md"
    format: "yaml-frontmatter"
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}
